---
- name: Initialize Kubernetes Control Plane
  hosts: controlplane
  become: yes
  become_method: sudo
  tasks:
    - name: Check if Kubernetes is already installed
      stat:
        path: /etc/kubernetes/admin.conf
      register: kube_init_check
      
    - name: Initialize kubeadm
      command: >
        kubeadm init
        --apiserver-advertise-address={{ ansible_facts['default_ipv4']['address'] }}
        --pod-network-cidr=192.168.0.0/16
        --node-name={{ inventory_hostname }}
      when: not kube_init_check.stat.exists

    - name: Create .kube directory
      file:
        path: /home/{{ ansible_user }}/.kube
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ ansible_user }}/.kube/config
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        remote_src: yes

    - name: Install Calico with Tigera Operator
      become: no
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.31.3/manifests/tigera-operator.yaml
        kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.31.3/manifests/custom-resources.yaml

    - name: Generate join command for worker nodes
      command: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command fact
      set_fact:
        join_command: "{{ join_command_raw.stdout }}"

- name: Join Kubernetes Worker Nodes to Control Plane
  hosts: workers
  become: yes
  tasks:
    - name: Check if node is already joined to the cluster
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: node_joined

    - name: Join the node to the Kubernetes cluster
      command: "{{ hostvars[groups['controlplane'][0]].join_command }} --node-name={{ inventory_hostname }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
      when: not node_joined.stat.exists
