apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-route
  namespace: argocd
spec:
  parentRefs:
    - name: secure-gw
      namespace: istio-system
  hostnames: 
    - "argocd.technologylab.uk"
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80