apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: zot-http-route
  namespace: container-registry
spec:
  parentRefs:
    - name: secure-gw
      namespace: istio-system
      sectionName: https
  hostnames: ["zot.technologylab.uk"]
  rules:
    - backendRefs:
        - name: zot
          port: 5000