apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  namespace: argocd
spec:
  project: homeautomation

  source:
    repoURL: git@github.com:danyalahmed/HomeLab.git
    targetRevision: main
    path: k8s/homeautomation/homeassistant

  destination:
    server: https://kubernetes.default.svc
    namespace: homeautomation

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
