apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Ensure this app syncs before others
spec:
  project: infrastructure
  source:
    repoURL: git@github.com:danyalahmed/technologylab.git
    targetRevision: HEAD
    path: argocd/infrastructure/metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true